version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: